import {
    Container, Grid
} from '@mui/material';
import LocationCityIcon from '@mui/icons-material/LocationCity';
import { Icon } from '@mui/icons-material';
import Box from '@mui/material/Box';

import styles from '@/styles/About.module.scss';

export default function About() {

    return (
        <section className={styles.about}>
            <Container>
                <div className={styles.hero_section}>
                    <h1><span>VCF is unique means of Financing and entails four components</span></h1>
                </div>
                <div className={styles.containerBox}> 
                <Grid container spacing={1} columns={{ xs: 4, sm: 8, md: 12 }} >
                    <Grid item xs={2} sm={4} md={6} >
                    <Box className={styles.boxCard}>
                            <LocationCityIcon className={styles.hero_icon}/>
                        </Box>
                    </Grid>
                    <Grid item xs={2} sm={4} md={6} >
                    <Box className={styles.boxCard}>
                            <LocationCityIcon className={styles.hero_icon}/>
                            </Box>
                    </Grid>
                    <Grid item xs={2} sm={4} md={6} >
                    <Box className={styles.boxCard}>
                            <LocationCityIcon className={styles.hero_icon}/>
                            </Box>
                    </Grid>
                    
                    <Grid item xs={2} sm={4} md={6} >
                        <Box className={styles.boxCard}>
                            <LocationCityIcon className={styles.hero_icon}/>
                        </Box>
                    </Grid>

                </Grid>
                </div>

                <div className={styles.text_container}>
                    <p>VCF can therefore be defined as the appropriation of value, generated by public sector intervention and private sector investment in relation to an underused asset (land and/or structure), for local re-investment to produce public good and potential private benefit.</p>
                    <p style={{ marginTop: "10px" }}>VCF maintains both an:</p>
                    <p>Inward rate of return: The revenue return for the private sector following initial investment; and
                        External rate of return: The proportion of this revenue which is reinvested in the same </p>
                    <p>development scheme for the public good.</p>
                </div>



            </Container>
        </section>
    )
}